[algorithm]
name = "algorithm"
switch = "--"
type = "c"
domain = ["as", "mmas", "eas", "ras", "acs"]

[localsearch]
name = "localsearch"
switch = "--localsearch "
type = "c"
domain = ["0", "1", "2", "3"]

[alpha]
name = "alpha"
switch = "--alpha "
type = "c"
domain = [
    "0.0",
    "0.1",
    "0.2",
    "0.3",
    "0.4",
    "0.5",
    "0.6",
    "0.7",
    "0.7",
    "0.8",
    "0.9",
    "1.0",
    "1.2",
    "1.3",
    "1.4",
    "1.5",
    "1.6",
    "1.7",
    "1.8",
    "1.9",
    "2.0",
    "2.1",
    "2.2",
    "2.3",
    "2.4",
    "2.5",
    "2.6",
    "2.7",
    "2.8",
    "2.9",
    "3.0",
    "3.1",
    "3.2",
    "3.3",
    "3.4",
    "3.5",
    "3.6",
    "3.7",
    "3.8",
    "3.9",
    "4.0",
    "4.1",
    "4.2",
    "4.3",
    "4.4",
    "4.5",
    "4.6",
    "4.6",
    "4.7",
    "4.8",
    "4.9",
    "5.0",
]

[beta]
name = "beta"
switch = "--beta "
type = "c"
domain = [
    "0.0",
    "1.25",
    "1.5",
    "2.5",
    "3.0",
    "3.75",
    "4.5",
    "5.0",
    "5.5",
    "6.0",
    "6.25",
    "7.0",
    "7.5",
    "8.75",
    "9.0",
    "9.5",
    "10.0",
]

[rho]
name = "rho"
switch = "--rho "
type = "c"
domain = [
    "0.01",
    "0.03",
    "0.05",
    "0.1",
    "0.15",
    "0.2",
    "0.25",
    "0.3",
    "0.35",
    "0.4",
    "0.45",
    "0.5",
    "0.55",
    "0.6",
    "0.65",
    "0.700",
    "0.750",
    "0.800",
    "0.850",
    "0.900",
    "0.950",
]

[ants]
name = "ants"
switch = "--ants "
type = "i"
domain = [5, 100]

[q0]
name = "q0"
switch = "--q0 "
type = "c"
domain = [
    "0.0",
    "0.03",
    "0.05",
    "0.1",
    "0.15",
    "0.2",
    "0.25",
    "0.3",
    "0.35",
    "0.4",
    "0.45",
    "0.5",
    "0.55",
    "0.6",
    "0.65",
    "0.700",
    "0.750",
    "0.800",
    "0.850",
    "0.900",
    "0.950",
]

[rasrank]
name = "rasrank"
switch = "--rasrank "
type = "i"
domain = [1, 100]

[elitistants]
name = "elitistants"
switch = "--elitistants "
type = "i"
domain = [1, 750]

[nnls]
name = "nnls"
switch = "--nnls "
type = "i"
domain = [5, 50]

[dlb]
name = "dlb"
switch = "--dlb "
type = "i"
domain = [0, 1]